name: main

on:
  schedule:
    - cron: '0 12 * * *'
            
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout REPO Content
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install discord.py
          python -m pip install openai.py
          
      - name: Execute PY Script
        env:
          DISCORD_TOKEN: OTU3MTI0MjQ1OTMzMTMzODM0.GacCsb.cIwHRufJznl-VmrVcaEQZIZWL_poLMqx3bwoQU
          AI_TOKEN: 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
        run: python bot.py
        
      
      
      
